### ISSUE TITLE
Implement a basic Discover section

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-seed-poc#5]
**Is your feature request related to a problem? Please describe.**
Implement a basic Discover section

**Describe the solution you'd like**
Use the design here: https://github.com/Stremio/stremio-design/blob/master/Discover%403x.png ; ignore the top nav bar

Use the `CatalogFiltered<MetaPreview>` model; stremio-core implements an elm-like architecture which fits with seed

The first two selects in the design are the `type` and `catalog` selectors. In the data type of `CatalogFiltered`, you only get `.catalogs` (vec of `CatalogEntry`); you will group those by type in order to achieve a two-level user friendly selector

The final selector (actually it can be more than one) represents the `.selectable_extra`, which for the default catalog of Cinemeta, is a genre selector

Look at the test in `src/lib` of stremio-core, it will also give you context on what actions need to be emitted in order to interact with `CatalogFiltered`

Because the selected type is contained in `.selected`, you won't need to keep any extra state in order to render it

**Additional context**
* default catalog: there should be an additional routing (related to #4) redirect of `/#/discover` to `/#/discover/{stringified default ResourceRequest}`; here's the default ResourceRequest: https://github.com/Stremio/stremio-core/blob/2b168cd1b6a9ce79f682dfb29765475d32e520ab/src/lib.rs#L189
* No need to implement the right info bar (just leave the space empty for now)
* Use native `<select>`, even though it doesn't look the same as the design

**Comment by MartinKavik** [comment]
**Report**

- Super basic Discover section (open on desktop Firefox) - https://stremio-seed-poc.netlify.com/
- Implemented:
  - `type`, `catalog` and `extra_props` selectors.
  - Reset button.
  - Meta previews (aka results) are selectable.
  - Integrated style.css from staging for faster feature development.
- Current working branch - https://github.com/MartinKavik/stremio-seed-poc/tree/discover_section

**Notes / Issues / Questions**

1. `Use native <select>` - it's a pain to work with them, because:
   - I've find out that some browsers don't fire mouse events for `select` element and  especially for `option`s. (That's why I recommended to open it in desktop Firefox).
   - I can't show custom value directly (e.g. `Animation, Action, Drama` on [design](https://github.com/Stremio/stremio-design/blob/master/Discover%403x.png)). I'm using hidden `option` as a workaround now.
   - I think it will be a pain to style it properly (e.g. group names are unreadable on the most platform with dark theme at the moment).
   - It changes completely its look once it's marked as `multiselect`. And `multiselect` is not very user-friendly. So we can't use `selects`'s values directly.
   - `select`s are not fully handled by Seed - there isn't a `value` attribute like in `inputs` and `select` can have more values - so it's not easy to handle it properly and don't break specifications (it's on my Seed's todo-list). I set `selects` values directly after the render at the moment.
   - **How multiselect should work? E.g.:**
        - Is it ok that option list disappears on click? (i.e. I have to open `select` every time I want to select more options)
        - User wants to deselect the last selected item when the prop is `required` or user wants to select options above `limit` => there's no feedback for these actions, is it ok?
    - **Should I continue to use native `select`** (and rewrite code a little bit to use `change` event on `select` instead of `click` on `options`s)?
    - I'm curious - what are the reasons to replace sidemenu with dropdowns for filtering? 

2. `selectable_extra`
    - https://github.com/Stremio/stremio-core/blob/463a82c9054ad6915796fbd89d6a4b30fa73fe17/src/state_types/models/catalogs.rs#L89
    - I think that there will be the most bugs - I'm trying to integrate it into POC according to comments but some API / small lib would be nice in the future.
    - It would be nice to have more testing data (i.e. more combinations of `is_required`, `options_limit`, etc.)

3. `OptionsLimit`
   - https://github.com/Stremio/stremio-core/blob/463a82c9054ad6915796fbd89d6a4b30fa73fe17/src/types/addons/manifest.rs#L34)
   - I think I can't use it because I can't construct `OptionsLimit` with custom value or compare it with `usize` => **can I implement at least public fn `new`?**
   - Is there a reason why is it `u32`? I assume that comparing with `usize` (from `Vec::len` or `Iterator::count`) will be the most used case.

4. `// NOTE: There's no currently selected preview item, cause some UIs may not have this`
    - https://github.com/Stremio/stremio-core/blob/463a82c9054ad6915796fbd89d6a4b30fa73fe17/src/state_types/models/catalogs.rs#L95
    - It's the only reason (at the moment) why I have to implement custom model and msg and I think it would be nice to have it so we save some time with implementation and it will be a little bit more consistent among platforms (I wasn't thinking about disadvantages, just a small tip).

**My next steps**
  1. Fix issues according to answers to questions above.
  1. Create PR.
  1. Implement simple router + page with player.
  1. Write other required routes.
  1. Redeploy + write report n.2.
  1. CSS

**Comment by Ivshti** [comment]
Hey,

@NikolaBorislavovHristov please provide feedback as well

1. The reason to use dropdown selects rather than the side menu is that addons may provide multiple selectable filters; this means that the side menu would have to fit multiple series of selectable variants, which would be confusing UX 
   - how to continue: do you think a custom component would be feasible/practical/relatively easy to make?
   - multiselects: disappearing on click is OK; re no feedback: it's currently OK
2. perhaps @NikolaBorislavovHristov can help you with a mock addon that would provide more data
3. you can change it to `usize` - there's no particular reason to use `u32`; also I don't quite get the issue, can't you `limit.0` to get the inner u32 (or usize)?
4. good point, hadn't thought of it; actually, if we implement it in the model, it might help the stremio-web implementation too, and if some platform doesn't want to use it, we don't lose much; @NikolaBorislavovHristov thoughts?

**Comment by MartinKavik** [comment]
> you can change it to usize - there's no particular reason to use u32; also I don't quite get the issue, can't you limit.0 to get the inner u32 (or usize)?

Ok, I'll try to change it to `usize`. I can't use inner `u32` because it's private. I'll create PR, we can discuss it there.

**Comment by Ivshti** [comment]
I'm ok with `struct OptionsLimit(pub usize)`

**Comment by NikolaBorislavovHristov** [comment]
1. i agree it's a pain to work native selects. the ux is terrible, especially for multiselect. and its not customizable
2. ive had the same issue so i created a sample test [addon](https://github.com/NikolaBorislavovHristov/stremio-pentest-addon) and add it to official addons json. i will add catalog resources soon, but you could alse try to do that.
4. lets keep ui and core separated, there must be a separate state container that holds the ui state like selected item, the `None` option etc

**Comment by Ivshti** [comment]
@NikolaBorislavovHristov re 3, that's the thing, `CatalogFiltered` already holds all of the information except the item to show on the preview; I agree, let's keep it separate, but if we go far in the development and this (the preview) is still the only thing we need a separate model for, I suggest we incorporate it in `CatalogFiltered`

@MartinKavik thoughts?

**Comment by MartinKavik** [comment]
> @MartinKavik thoughts?

1. Native selects - I'll try to implement the simplest alternative and I'll report result.
1. Test addon - I'll look at @NikolaBorislavovHristov addon (thanks), but it's not a blocker for me and there are tasks with higher priority for me at the moment.
1. OptionsLimit - I'll create a PR with `struct OptionsLimit(pub usize)`.
1. Selected preview item - If we are able to save UI state on all platforms then I can agree with @NikolaBorislavovHristov to keep core and ui separated but a little bit more documentation would be nice - e.g. Should I clear the selected preview id when the filter is changing? Should I preselect the first preview? etc.

**Comment by Ivshti** [comment]
4. preselect the first one; please keep track of stuff that need more documentation so we can address them at some point

**Comment by NikolaBorislavovHristov** [comment]
4. you could preselect the first item. on android, ios and on small screen sizes for web there is no preview at all, so there is no place for this in the core.

**Comment by Ivshti** [comment]
ah yes, so that settles it - this is not gonna be in core

**Comment by MartinKavik** [comment]
Done.

_Notes:_ There are custom selects instead of the native ones.
