### ISSUE TITLE
Update to the latest CSS

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-seed-poc#6]
**Is your feature request related to a problem? Please describe.**
The CSS is outdated

**Describe the solution you'd like**
Get the latest CSS from stremio-web and update the DOM structure accordingly

**Additional context**
Ask @NikolaBorislavovHristov on how to do it, he'll probably send a blob generated from recursively walking the stremio-web source tree and compiling all LESS files into a CSS blob

**Comment by MartinKavik** [comment]
PoC logic should be complete (https://stremio-seed-poc.netlify.com/), but it's still ugly.
- **A)** Should I integrate compiled CSS and style it?
- **B)** Or create a build pipeline for LESS and then style it?

Ad **A)** - @NikolaBorislavovHristov  is it a trivial task for you to send me generated CSS or I'll compiled it by myself otherwise.

Ad **B)** - I can't find Rust compiler for LESS. Should I write build pipeline for NodeJS or do you have a favorite way / compiler? (There are some Rust SASS compilers as the alternative, but I don't have experience with them because I'm using TailwindCSS for my projects.)

**Comment by Ivshti** [comment]
doesn't have to be a rust compiler, we can just temporarily make a JS script that would build the CSS

regarding the other things, @NikolaBorislavovHristov should provide input

**Comment by NikolaBorislavovHristov** [comment]
The easiest way to get compiled css is to run `yarn build` in stremio-web and then extract the css from the content of the style tag in the `/dist/index.html` file

**Comment by MartinKavik** [comment]
Done.

More info: https://github.com/Stremio/stremio-seed-poc/issues/3#issuecomment-560017411
